### ISSUE TITLE
Restoring `.stack-work` causing projects to not be rebuilt

### ISSUE THREAD

**Issue by eriknstevenson** [mfine/heroku-buildpack-stack#17]
I believe 1819e0c introduced an issue that is causing projects to not be properly rebuilt. I'm not sure I know enough about stack or heroku's inner-workings to know for sure what exactly is going on here. Perhaps I'm doing something dumb, but I've been messing around with it for a while and am having no luck except for when I use the buildpack prior to the introduction of `.stack-work` caching.

The following is a log taken from me deploying a heroku application running using the latest version of the buildpack. I had modified the application's haskell source code and introduced compiler errors, but as you can see the application still deployed successfully. Additionally, when stack/ghc _does_ recompile, there should be a line such as: 

```
[1 of 1] Compiling Main ( src/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/nsv/nsv-tmp/Main.o )
```

which is also missing from the log.

> -----> Haskell app detected
> -----> 2016-09-16_20:43:50 Starting...
> -----> 2016-09-16_20:43:50 Exporting config vars
> -----> 2016-09-16_20:43:50 Restoring 6.0.0a files from cache
> -----> 2016-09-16_20:43:50 Restoring stack-1.2.0
> -----> 2016-09-16_20:43:50 Substituting stack vars
> -----> 2016-09-16_20:43:51 Restoring .stack-work
> -----> 2016-09-16_20:43:51 Running stack
> stack will use a sandboxed GHC it installed
> For more information on paths, see 'stack path' and 'stack exec env'
> To use this GHC and packages outside of a project, consider using:
> stack ghc, stack ghci, stack runghc, or stack exec
> nsv-0.1.0.0: configure
> Configuring nsv-0.1.0.0...
> nsv-0.1.0.0: build
> Preprocessing executable 'nsv' for nsv-0.1.0.0...
> nsv-0.1.0.0: copy/register
> Installing executable(s) in
> /app/.stack-work/install/x86_64-linux/lts-7.0/8.0.1/bin
> Copying from /app/.stack-work/install/x86_64-linux/lts-7.0/8.0.1/bin/nsv to /app/.local/bin/nsv
> Copied executables to /app/.local/bin:
> -nsv
> -----> 2016-09-16_20:43:53 Making stack binaries available
> -----> 2016-09-16_20:43:54 Caching .stack-work
> -----> 2016-09-16_20:43:54 Finished!
> -----> Discovering process types
>        Procfile declares types -> web
> -----> Compressing...
>        Done: 19.4M
> -----> Launching...
>        Released v9
>        https://radiant-tor-47956.herokuapp.com/ deployed to Heroku

I can provide more logs and configuration settings if necessary, but would be curious to know if others are noticing the same thing.

Obviously, caching as much as possible is very beneficial and decreases the time it takes to deploy, but at the moment it seems to be redeploying the same code over and over, despite any changes made to the repository.

**Comment by mfine** [comment]
Bummer - will try and reproduce with a simple case and see what's going on. Nothing off the top of my head would suggest why preserving the `.stack-work` would cause compile errors to be ignored.

**Comment by eriknstevenson** [comment]
I don't think it's ignoring compiler errors. It's not recompiling. It's as if stack doesn't recognize that any files have changed so it doesn't attempt to recompile. 

I appreciate you looking into it and I'm interested to see if you can get it to repro.

**Comment by mfine** [comment]
@narrative didn't have the time to reproduce this on heroku yet, but was able to see something similar just locally with stack:
1. successfully build
2. introduce an error in the source
3. roughly touch all the files under `.stack-work` (`find .stack-work | xargs touch`)
4. try building again and succeed - no build error

So doh, the copying from the cache wasn't preserving timestamps - so potentially that is the problem? I just posted a simple fix - b979539 - let me know if that resolves things for you!

**Comment by mfine** [comment]
Was able to verify the fix on heroku as well. Let me know if you continue to see issues. Sorry for the problems - scary!

**Comment by eriknstevenson** [comment]
Thanks for the fix!
