### ISSUE TITLE
Latest Makefile support commit breaking builds

### ISSUE THREAD

**Issue by iand675** [mfine/heroku-buildpack-stack#23]
I have a repo without a Makefile, and my latest pushes are failing with the following error:

```
make: *** No rule to make target `install'.  Stop.
 !     Push rejected, failed to compile Haskell app.
 !     Push failed
```

It would appear that the logic for detecting a Makefile must be flawed in some fashion.

**Comment by mfine** [comment]
@iand675 thanks for the report - rolled back the change.

The logic is pretty straightforward:

```bash
if [ -f "Makefile" ]; then
    speak "Makefile detected"
    make
    make install
```

Did you see the trace `Makefile detected`? It seems like the first call to `make` succeeded? Do you have a `Makefile` file present in your directory?

**Comment by mfine** [comment]
Also, if you have a minimal example I could reproduce with, that would be great.

**Comment by mfine** [comment]
@iand675 I think this might be an issue where there's a Makefile lying around - changed the logic to look for the makefile in the pushed directory contents - 8e524bcf96903c40a909572afbd2263154086674.

**Comment by mfine** [comment]
Was able to verify that there was a `Makefile` lying around in Heroku's building directory - the logic was picking up that `Makefile`. The logic's been changed to check the `Makefile` in the customer supplied directory - that should fix issues. Apologies for the problems this caused.

**Comment by iand675** [comment]
No worries. Thanks for the quick fix! 😄
