### ISSUE TITLE
Default build behaviour compiles without optimizations

### ISSUE THREAD

**Issue by fosskers** [mfine/heroku-buildpack-stack#30]
The default behaviour of the `compile` script seems to be to build executables with `--fast`, which disables optimization flags specified in `.cabal`:

https://github.com/mfine/heroku-buildpack-stack/blob/2d8edb280a0039dbf3a3746a5f15478cd2bd96fb/bin/compile#L103

Is this intended?

**Comment by mfine** [comment]
@fosskers it was - used it early on to get around long compile times and build timeouts. With the makefile now in place, there's alternatives I guess to getting a fast build. Will remove.

**Comment by fosskers** [comment]
Damn, quick turnaround! Thanks.

**Comment by mfine** [comment]
Thanks for the issue - and apologies for the inconvenience of the default.

**Comment by fosskers** [comment]
Not a problem, thank you.
