### ISSUE TITLE
cache not kept ?

### ISSUE THREAD

**Issue by nrolland** [mfine/heroku-buildpack-stack#4]
I would have expected libraries to be persisted in the cache but they seem to be downloaded every time.
any idea why ?

**Comment by mfine** [comment]
@nrolland do you have some output of repeated calls with the downloads happening? Could you paste it into the issue?

**Comment by nrolland** [comment]
this happened only after no successful build which makes sense and must be part of heroku way of doing things i guess.

btw, to debug my unsuccessful build, I bashed in a local heroku environment (from heroku:cedar), mounted a local copy of the buildpack , added an invocation to "bash" in the middle of compile script, and invoked it manually on the mounted project, from the VM : this is dead efficient to see pb.
if that help I can make a small video of the setup.

**Comment by mfine** [comment]
That makes sense - only on a successful build are things cached.
